version: '3'
services:
  webapp:
    build: .
    image: moheane/webapp
    ports:
      - 3000:3000
    volumes:
      - ./:/app:ro
  
  mongodb:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    
